### ISSUE TITLE
360 images

### ISSUE THREAD

**Issue by noAlvaro** [jonastreub/VRComponent#2]
Fantastic job, man... such a precious and timely addition to **Framer.js**, congrats!

I would just suggest to extend the current _cubmap technique_ to support _360 images_ like the one below. Many times this is the type of asset we have at hand.

![360 image sample](https://upload.wikimedia.org/wikipedia/commons/6/65/SonyCenter_360panorama.jpg)

Thanks!

**Comment by jornvandijk** [comment]
Thanks for the suggestion! Do you have a good resource site where we can find these assets?

**Comment by jonastreub** [comment]
@noAlvaro sphere maps need WebGL to be rendered. It might be worth the effort though. I'll try if it is performant. In the meantime you could turn your sphere maps into a cube maps as explained by Paul in [this article](https://aerotwist.com/tutorials/create-your-own-environment-maps/).

**Comment by noAlvaro** [comment]
Thanks, @jonastreub!

@jornvandijk, [here](https://www.dropbox.com/sh/yaj0rzvs35phlox/AAAOMM8tzX8-ieVHF8ddefv9a?dl=0) you can download some pictures I've collected for testing purposes. But I found some sites, also:

* [HDRI Hub](https://www.hdri-hub.com)
* [VizPeople](http://www.viz-people.com)

Just to notice: some files in these sites come in _.hdr_ format. Never used, though.

Hope it helps!

**Comment by jornvandijk** [comment]
Thanks!

**Comment by jonastreub** [comment]
I updated the readme with a link to the following [tool](http://gonchar.me/panorama/) which can convert your spherical panoramas to cube map.
