### ISSUE TITLE
Unable to navigate after the first drag

### ISSUE THREAD

**Issue by bencross95** [jonastreub/VRComponent#3]
Unable to navigate after the first drag after the latest Framer update.

The prototype in question: [https://framer.cloud/quZbq/](url)

Also some glitches with the new dampening feature, but I find it hard to replicate the issue.

**Comment by patrykadas** [comment]
I've got the same. Any ideas?

**Comment by jonastreub** [comment]
I missed this. I'll look into it tomorrow

**Comment by patrykadas** [comment]
@jonastreub Thank you! If I could be a help here just please let me know.
