### ISSUE TITLE
Opportunity for adding Controllers

### ISSUE THREAD

**Issue by noAlvaro** [jonastreub/VRComponent#4]
Hello again...

Time passed by and most mobile VR headsets are now bundled with controllers. And as they are not motion tracked, it seems that there's a good momentum and opportunity to use an external smartphone device to point/control VR component prototypes on the desktop using `deviceorientation` events.

I tried implementing this for a little while, using web sockets and bluetooth pairing requests, though with no success at all. Most of the times I was getting blocked with an issue of Framer Studio's architecture. As a designer I couldn't get there, but maybe you could have better luck :)

Just saying.

**Comment by jonastreub** [comment]
For controllers to work the component would need to support some kind of ray tracing. While this would be cool I currently don't think it is worth the effort. If you want to prototype with controllers I would recommend trying out [A-Frame](https://aframe.io) or [React VR](https://facebook.github.io/react-vr/).
