### ISSUE TITLE
Preview on mobile browser not working properly

### ISSUE THREAD

**Issue by aravindravi** [jonastreub/VRComponent#5]
With the new Framer update, the rendering on Android mobile phone shows colored squares with flickering. None of the images are rendering properly. However, when an older project is saved (without Framer design mode)  and changes are made to that, it still works. 

![image](https://user-images.githubusercontent.com/5208612/27118031-2ff7fc00-508e-11e7-921a-499b15f77414.png)

**Comment by jonastreub** [comment]
I updated the component and library. Could you check if the three example in the readme work as expected? Thanks for the heads-up.
