### ISSUE TITLE
Component only works on canvas mode & desktop browsers

### ISSUE THREAD

**Issue by TDMW** [jonastreub/VRComponent#6]
I suspect this might have something to do with the big Framer update, but I can't get the VR component to work on phones (Framer App + browsers) and even in Framer itself if I use anything else besides the canvas size. It just shows a white screen and when opened in a browser on mobile it shows an error. For some reason 'Canvas' and desktop browsers do work.

**Comment by ebpo90** [comment]
I'm having the same issue. The webview crashes after some seconds of a messy preview.

**Comment by aravindravi** [comment]
I'm having the same issue and reported a bug too. The component is buggy with the new Framer update.

**Comment by jonastreub** [comment]
The component wasn't compatible with the latest Framer library because of the change from pixels to points. Both the library and the component just got an update and should work as expected. The three examples from the readme have been updated. When you update the component be sure to also update the library from the File menu.

**Comment by edbpo** [comment]
Updated component and library but still not working on mobile. When I open the project inside Framer app or Safari I can see the images from the cube unaligned and flashing for some seconds, if I start moving around it just goes blank.

**Comment by jonastreub** [comment]
Could you check with my example: https://framer.cloud/pzkuO

**Comment by aravindravi** [comment]
The example isn't working for me either, on an Android phone.

**Comment by jonastreub** [comment]
I just tested the example on a Samsung S6 and it worked as expected. What device are you on @aravindravi ?

**Comment by edbpo** [comment]
Example also not working on iPhone SE.

**Comment by jonastreub** [comment]
Unfortunately I have not been able to reproduce any issues on iOS or Android using the updated component. What iOS version are you on?

**Comment by aravindravi** [comment]
I tried it on LG G4 with the Framer web view.
